/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class UsbPort */

#ifndef _Included_UsbPort
#define _Included_UsbPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     UsbPort
 * Method:    openUsb
 * Signature: (SS)I
 */
JNIEXPORT jint JNICALL Java_UsbPort_openUsb
  (JNIEnv *, jobject, jshort, jshort);

/*
 * Class:     UsbPort
 * Method:    readUsb
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_UsbPort_readUsb
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     UsbPort
 * Method:    writeUsb
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_UsbPort_writeUsb
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     UsbPort
 * Method:    closeUsb
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_UsbPort_closeUsb
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
